### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by szcomanche** [quran/quran.com-api#332] opened 2021-04-25 08:35 UTC

**Comment by benomaire** [comment] 2021-04-26 13:30
possible duplicate of #333

**Comment by AbirRazzak** [comment] 2021-04-29 04:10
@szcomanche Can you please provide some more detail on the bug?

**Comment by AbirRazzak** [comment] 2021-05-05 20:01
Closing due to inactivity. Please let us know if you continue seeing issues related to this.

**Closed by AbirRazzak** 2021-05-05 20:01 UTC
Labels: invalid
