### ISSUE TITLE
[Tafsirs]: getting 404 Not Found HTML page.. instead of JSON response.

### ISSUE THREAD

**Issue by AbdulQadeer19** [quran/quran.com-api#297] opened 2021-02-10 15:09 UTC
First of all you guys did great job I'm myself also developer. While just checking your api's.
`/chapters/{chapter_id}/verses/{verse_id}/tafsirs` 
It return nothing.

![image](https://user-images.githubusercontent.com/75783622/107528258-70d5c600-6bdb-11eb-9172-b782eb8f4282.png)

**Comment by naveed-ahmad** [comment] 2021-02-10 16:46
Checkout v4 https://quran.api-docs.io/v4/getting-started/introduction tafisr and some other endpoint were never implemented/finished in v3.

**Comment by AbirRazzak** [comment] 2021-04-29 16:59
Not a bug, just not implemented yet. Closing for now.

**Closed by AbirRazzak** 2021-04-29 16:59 UTC
